

export const metadata = {
  title: 'TRYFM PROJEKT',
  description: 'Generated by Tryfm',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
